[package]
name = "riscv_baremetal"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = "0.11"
riscv-rt = "0.12"
panic-halt = "0.2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
