[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

# Uncomment to use RISC-V GCC linker instead
# [target.riscv32imac-unknown-none-elf]
# linker = "riscv32-unknown-elf-gcc"
# rustflags = [
#   "-C", "link-arg=-nostartfiles",
#   "-C", "link-arg=-Tlink.x",
# ]
