[package]
name = "lighting"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "0.19"
winit = "0.29"
env_logger = "0.11"
log = "0.4"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
cgmath = "0.18"

[[bin]]
name = "lighting"
path = "src/main.rs"
